---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: dealer
  template:
    metadata:
      labels:
        app: dealer
    spec:
      containers:
      - name: deck
        image: 833104194858.dkr.ecr.us-east-1.amazonaws.com/qa-bootcamp_dealer:ec42768c60c757831d0c0c8b1213252e8c0ed592
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dealer
spec:
  selector:
    app: dealer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
