---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: dealer
  template:
    metadata:
      labels:
        app: dealer
    spec:
      containers:
      - name: deck
        image: 833104194858.dkr.ecr.us-east-1.amazonaws.com/qa-bootcamp_dealer:0f027c3ba56499076bff6a57a68e15dbd0e87587
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dealer
spec:
  selector:
    app: dealer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
