---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: dealer
  template:
    metadata:
      labels:
        app: dealer
    spec:
      containers:
      - name: dealer
        image: 833104194858.dkr.ecr.us-east-1.amazonaws.com/qa-bootcamp_dealer:50c63f9c204d08695467add1e1376f96075fcd39
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dealer
spec:
  selector:
    app: dealer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
