---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: deck
  template:
    metadata:
      labels:
        app: deck
    spec:
      containers:
      - name: deck
        image: 833104194858.dkr.ecr.us-east-1.amazonaws.com/qa-bootcamp_deck:21c10ab157f84a038507865bbf8e4c7cf193422e
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deck
spec:
  selector:
    app: deck
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
