---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
      - name: games
        image: 833104194858.dkr.ecr.us-east-1.amazonaws.com/qa-bootcamp_games:60fd97c5f91edbee12708b850aee2d57d2068cdb
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: games
spec:
  selector:
    app: games
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
